/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OldSportcar({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/old-sportcar.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.89, 0]} scale={[0.98, 1, 1]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.red} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.dark} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.gray} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['interior ']} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials.yellow} />
        <mesh geometry={nodes.Cube_6.geometry} material={materials.interior2} />
      </group>
    </group>
  )
}

useGLTF.preload('/old-sportcar.glb')
